;;; engraved-theme.el -*- lexical-binding: t; -*-

(require 'engrave-faces)

(add-to-list 'engrave-faces-themes
             '(doom-opera-light
               (default :short "default" :slug "D" :family "JetBrains Mono" :foreground "#2a2a2a" :background "#fafafa" :slant normal :weight regular)
               (bold :short "bold" :slug "b" :weight bold)
               (italic :short "italic" :slug "i" :slant italic)
               (variable-pitch :short "var-pitch" :slug "vp" :family "Overpass" :height 196)
               (shadow :short "shadow" :slug "h" :foreground "#9e9e9e")
               (success :short "success" :slug "sc" :foreground "#4f894c")
               (warning :short "warning" :slug "w" :foreground "#9a7500")
               (error :short "error" :slug "e" :foreground "#99324b")
               (link :short "link" :slug "l" :foreground "#3b6ea8" :weight bold)
               (link-visited :short "link" :slug "lv" :foreground "#8b008b" :weight bold)
               (highlight :short "link" :slug "hi" :foreground "#fafafa" :background "#3b6ea8")
               (font-lock-comment-face :short "fl-comment" :slug "c" :foreground "#b1b1b1")
               (font-lock-comment-delimiter-face :short "fl-comment-delim" :slug "cd" :foreground "#b1b1b1")
               (font-lock-string-face :short "fl-string" :slug "s" :foreground "#4f894c")
               (font-lock-doc-face :short "fl-doc" :slug "d" :foreground "#b6b6b6")
               (font-lock-doc-markup-face :short "fl-doc-markup" :slug "m" :foreground "#97365b")
               (font-lock-keyword-face :short "fl-keyword" :slug "k" :foreground "#3b6ea8")
               (font-lock-builtin-face :short "fl-builtin" :slug "bi" :foreground "#29838d")
               (font-lock-function-name-face :short "fl-function" :slug "f" :foreground "#29838d")
               (font-lock-variable-name-face :short "fl-variable" :slug "v" :foreground "#cb9aad")
               (font-lock-type-face :short "fl-type" :slug "t" :foreground "#9a7500")
               (font-lock-constant-face :short "fl-constant" :slug "o" :foreground "#97365b")
               (font-lock-warning-face :short "fl-warning" :slug "wr" :foreground "#9a7500")
               (font-lock-negation-char-face :short "fl-neg-char" :slug "nc" :foreground "#3b6ea8" :weight bold)
               (font-lock-preprocessor-face :short "fl-preprocessor" :slug "pp" :foreground "#3b6ea8" :weight bold)
               (font-lock-regexp-grouping-construct :short "fl-regexp" :slug "rc" :foreground "#3b6ea8" :weight bold)
               (font-lock-regexp-grouping-backslash :short "fl-regexp-backslash" :slug "rb" :foreground "#3b6ea8" :weight bold)
               (org-block :short "org-block" :slug "ob" :background "#e0e0e0")
               (org-block-begin-line :short "org-block-begin" :slug "obb" :foreground "#b1b1b1" :background "#e0e0e0")
               (org-block-end-line :short "org-block-end" :slug "obe" :foreground "#b1b1b1" :background "#e0e0e0")
               (outline-1 :short "outline-1" :slug "Oa" :foreground "#3b6ea8" :weight extra-bold :height 1.25)
               (outline-2 :short "outline-2" :slug "Ob" :foreground "#97365b" :weight bold :height 1.15)
               (outline-3 :short "outline-3" :slug "Oc" :foreground "#842879" :weight bold :height 1.12)
               (outline-4 :short "outline-4" :slug "Od" :foreground "#6c92bd" :weight semi-bold :height 1.09)
               (outline-5 :short "outline-5" :slug "Oe" :foreground "#b16883" :weight semi-bold :height 1.06)
               (outline-6 :short "outline-6" :slug "Of" :foreground "#9db6d3" :weight semi-bold :height 1.03)
               (outline-7 :short "outline-7" :slug "Og" :foreground "#cb9aad" :weight bold)
               (outline-8 :short "outline-8" :slug "Oh" :foreground "#d7e2ed" :weight semi-bold)
               (highlight-numbers-number :short "hl-number" :slug "hn" :foreground "#97365b" :weight bold)
               (highlight-quoted-quote :short "hl-qquote" :slug "hq" :foreground "#3b6ea8")
               (highlight-quoted-symbol :short "hl-qsymbol" :slug "hs" :foreground "#9a7500")
               (rainbow-delimiters-depth-1-face :short "rd-1" :slug "rda" :foreground "#3b6ea8")
               (rainbow-delimiters-depth-2-face :short "rd-2" :slug "rdb" :foreground "#97365b")
               (rainbow-delimiters-depth-3-face :short "rd-3" :slug "rdc" :foreground "#4f894c")
               (rainbow-delimiters-depth-4-face :short "rd-4" :slug "rdd" :foreground "#842879")
               (rainbow-delimiters-depth-5-face :short "rd-5" :slug "rde" :foreground "#29838d")
               (rainbow-delimiters-depth-6-face :short "rd-6" :slug "rdf" :foreground "#3b6ea8")
               (rainbow-delimiters-depth-7-face :short "rd-7" :slug "rdg" :foreground "#97365b")
               (rainbow-delimiters-depth-8-face :short "rd-8" :slug "rdh" :foreground "#4f894c")
               (rainbow-delimiters-depth-9-face :short "rd-9" :slug "rdi" :foreground "#842879")))
